name: Publish to Dockerhub

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'run'
        required: true
        type: choice
        options:
          - run


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get lowercase repo name
        id: repo_name
        run: echo "REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Check reponame lowercase
        run: echo ${{ env.REPO_NAME }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64, linux/arm/v7
          push: true
          tags: |
            ${{ env.REPO_NAME }}:latest
